import Head from 'next/head'
import Banner from '../components/Banner'


export default function Home() {

  

  return (
    <div>
      
      <Head>
        <title>FreeCoinFlow</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className='grid grid-cols-1 place-items-center'>
        <Banner />
    
    
      </main>

   
    </div>
  )
}

// This function gets called at build time on server-side.
// It won't be called on client-side, so you can even do
// direct database queries.
// export async function getStaticProps() {
//   // Fetch products data for the landing page by request to "http://localhost:3000/api/products" route.
//   const products = await fetch("http://localhost:3000/api/products").then(res => res.json())
//   return {
//     props: {
//       products
//     },
//   }
// }