import Head from 'next/head'
import Banner from '../components/Banner'


export default function Home() {

  

  return (
    <div>
      
      <Head>
        <title>Neoflow</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className='grid grid-cols-1 place-items-center'>
        <Banner />
    
    
      </main>

   
    </div>
  )
}
