const offering = {
    "BTC":{
        "USD":[
            {
                uid:"0",
              buyOfferNO:0,
              transactionType:"buy",
              addressType:"public address",
              currency:"USD",
              crypto:"BTC",
              payment:"All Payments",
              price:38063.46,
              available:108.88,
              min:20,
              max:50,
            },
            {
                uid:"1",
                buyOfferNO:3,
                transactionType:"buy",
                addressType:"public address",
                currency:"USD",
                crypto:"BTC",
                payment:"All Payments",
                price:38065.64,
                available:80.1,
                min:20,
                max:50,
            },
            {
                uid:"2",
                buyOfferNO:6,
                transactionType:"buy",
                addressType:"public address",
                currency:"USD",
                crypto:"BTC",
                payment:"All Payments",
                price:38060.8,
                available:70.14,
                min:5,
                max:5000,
            },
        ],
        "THB":[
            {
                uid:"3",
                buyOfferNO:9,
                transactionType:"buy",
                addressType:"public address",
                currency:"THB",
                crypto:"BTC",
                payment:"All Payments",
                price:1240000,
                available:50.35,
                min:500,
                max:500000,
              },
            {
                uid:"4",
                buyOfferNO:12,
                transactionType:"buy",
                addressType:"public address",
                currency:"THB",
                crypto:"BTC",
                payment:"All Payments",
                price:1241515.05,
                available:80.35,
                min:10,
                max:1300000,
              },
            {
                uid:"5",
                buyOfferNO:15,
                transactionType:"buy",
                addressType:"public address",
                currency:"THB",
                crypto:"BTC",
                payment:"All Payments",
                price:1241705.89,
                available:70.35,
                min:10,
                max:1300000,
              },
            {
                uid:"6",
                buyOfferNO:18,
                transactionType:"buy",
                addressType:"public address",
                currency:"THB",
                crypto:"BTC",
                payment:"All Payments",
                price:1241549.9,
                available:70.35,
                min:10,
                max:1300000,
              },
           
        ],
    },
    "ETH":{
        "USD":[
            {
                uid:"0",
                buyOfferNO:1,
              transactionType:"buy",
              addressType:"public address",
              currency:"USD",
              crypto:"ETH",
              payment:"All Payment",
              price:2668.64,
              lable:319.325,
              min:25,
              max:3500,
            },
            {
                uid:"1",
                  buyOfferNO:4,
                transactionType:"buy",
                addressType:"public address",
                currency:"USD",
                crypto:"ETH",
                payment:"All Payments",
                price:2670.31,
                available:256.5,
                min:15,
                max:3500,
              },
            {
                uid:"2",
                  buyOfferNO:7,
                transactionType:"buy",
                addressType:"public address",
                currency:"USD",
                crypto:"ETH",
                payment:"All Payments",
                price:2670.31,
                available:202.2,
                min:10,
                max:4500,
              },
        ],
        "THB":[
            {
                uid:"3",
                buyOfferNO:10,
                transactionType:"buy",
                addressType:"public address",
                currency:"THB",
                crypto:"ETH",
                payment:"Bank Transfer",
                price:86999,
                available:50.35,
                min:800,
                max:480000,
              },
            {
                uid:"4",
                buyOfferNO:13,
                transactionType:"buy",
                addressType:"public address",
                currency:"THB",
                crypto:"ETH",
                payment:"Bank Transfer",
                price:87771.49,
                available:500,
                min:800,
                max:5000000,
              },
            {
                uid:"5",
                buyOfferNO:16,
                transactionType:"buy",
                addressType:"public address",
                currency:"THB",
                crypto:"ETH",
                payment:"Bank Transfer",
                price:87519.7,
                available:500,
                min:800,
                max:5000000,
              },
            {
                uid:"6",
                buyOfferNO:19,
                transactionType:"buy",
                addressType:"public address",
                currency:"THB",
                crypto:"ETH",
                payment:"Bank Transfer",
                price:87502.35,
                available:500,
                min:800,
                max:5000000,
              },
        ]
    },
    "USDC":{
        "USD":[
            {
                uid:"0",
                buyOfferNO:2,
              transactionType:"buy",
              addressType:"public address",
              currency:"USD",
              crypto:"USDC",
              payment:"All Payments",
              price:1,
              available:319.325,
              min:25,
              max:3500,
            },
            {
                uid:"1",
                  buyOfferNO:5,
                transactionType:"buy",
                addressType:"public address",
                currency:"USD",
                crypto:"USDC",
                payment:"All Payments",
                price:1,
                available:325.5,
                min:10,
                max:4000,
              },
            {
                uid:"2",
                  buyOfferNO:8,
                transactionType:"buy",
                addressType:"public address",
                currency:"USD",
                crypto:"USDC",
                payment:"All Payments",
                price:1,
                available:2000,
                min:5,
                max:6000,
              }, 
        ],
        "THB":[
            {
                uid:"3",
                buyOfferNO:11,
                transactionType:"buy",
                addressType:"public address",
                currency:"THB",
                crypto:"USDC",
                payment:"Bank Transfer",
                price:32.24,
                available:50.35,
                min:800,
                max:480000,
              },
              {
                  uid:"4",
                buyOfferNO:14,
                transactionType:"buy",
                addressType:"public address",
                currency:"THB",
                crypto:"USDC",
                payment:"Bank Transfer",
                price:32.27,
                available:8000,
                min:32,
                max:640000,
              },
            {
                uid:"5",
                buyOfferNO:17,
                transactionType:"buy",
                addressType:"public address",
                currency:"THB",
                crypto:"USDC",
                payment:"Bank Transfer",
                price:32.27,
                available:8000,
                min:32,
                max:640000,
              },
            {
                uid:"6",
                buyOfferNO:20,
                transactionType:"buy",
                addressType:"public address",
                currency:"THB",
                crypto:"USDC",
                payment:"Bank Transfer",
                price:32.30,
                available:8000,
                min:32,
                max:640000,
              },
        ]
    }
}
export default offering;