const offering = {
    "BTC":{
        "USD":[
            {
                uid:"0",
                sellOfferNO:0,
                transactionType:"sell",
                addressType:"public address",
                currency:"USD",
                crypto:"BTC",
                payment:"All Payments",
                price:38063.46,
                available:108.88,
                min:20,
                max:50,
            },
            {
                uid:"1",
                sellOfferNO:3,
                transactionType:"sell",
                addressType:"public address",
                currency:"USD",
                crypto:"BTC",
                payment:"All Payments",
                price:38065.64,
                available:80.1,
                min:20,
                max:50,
                },
            {
                uid:"2",
                sellOfferNO:6,
                transactionType:"sell",
                addressType:"public address",
                currency:"USD",
                crypto:"BTC",
                payment:"All Payments",
                price:38060.8,
                available:70.14,
                min:5,
                max:5000,
                },
        ],
        "THB":[
            {
                uid:"3",
                sellOfferNO:9,
                transactionType:"sell",
                addressType:"public address",
                currency:"THB",
                crypto:"BTC",
                payment:"All Payments",
                price:1240000,
                available:50.35,
                min:500,
                max:500000,
                },
            {
                uid:"4",
                sellOfferNO:12,
                transactionType:"sell",
                addressType:"public address",
                currency:"THB",
                crypto:"BTC",
                payment:"All Payments",
                price:1241515.05,
                available:80.35,
                min:10,
                max:1300000,
                },
            {
                uid:"5",
                sellOfferNO:15,
                transactionType:"sell",
                addressType:"public address",
                currency:"THB",
                crypto:"BTC",
                payment:"All Payments",
                price:1241705.89,
                available:70.35,
                min:10,
                max:1300000,
                },
            {
                uid:"6",
                sellOfferNO:18,
                transactionType:"sell",
                addressType:"public address",
                currency:"THB",
                crypto:"BTC",
                payment:"All Payments",
                price:1241549.9,
                available:70.35,
                min:10,
                max:1300000,
                },
        ],
    },
    "ETH":{
        "USD":[
            {
                uid:"0",
                sellOfferNO:1,
                transactionType:"sell",
                addressType:"public address",
                currency:"USD",
                crypto:"ETH",
                payment:"All Payments",
                price:2668.64,
                lable:319.325,
                min:25,
                max:3500,
            },
            {
                uid:"1",
                sellOfferNO:4,
                transactionType:"sell",
                addressType:"public address",
                currency:"USD",
                crypto:"ETH",
                payment:"All Payments",
                price:2670.31,
                available:256.5,
                min:15,
                max:3500,
            },
            {
                uid:"2",
                sellOfferNO:7,
                transactionType:"sell",
                addressType:"public address",
                currency:"USD",
                crypto:"ETH",
                payment:"All Payments",
                price:2670.31,
                available:202.2,
                min:10,
                max:4500,
            },
        ],
        "THB":[
            {
                uid:"3",
                sellOfferNO:10,
                transactionType:"sell",
                addressType:"public address",
                currency:"THB",
                crypto:"ETH",
                payment:"Bank Transfer",
                price:86999,
                available:50.35,
                min:800,
                max:480000,
            },
            {
                uid:"4",
                sellOfferNO:13,
                transactionType:"sell",
                addressType:"public address",
                currency:"THB",
                crypto:"ETH",
                payment:"Bank Transfer",
                price:87771.49,
                available:500,
                min:800,
                max:5000000,
            },
            {
                uid:"5",
                sellOfferNO:16,
                transactionType:"sell",
                addressType:"public address",
                currency:"THB",
                crypto:"ETH",
                payment:"Bank Transfer",
                price:87519.7,
                available:500,
                min:800,
                max:5000000,
            },
            {
                uid:"6",
                sellOfferNO:19,
                transactionType:"sell",
                addressType:"public address",
                currency:"THB",
                crypto:"ETH",
                payment:"Bank Transfer",
                price:87502.35,
                available:500,
                min:800,
                max:5000000,
            },
        ]
    },
    "USDC":{
        "USD":[
            {
                uid:"0",
              sellOfferNO:2,
              transactionType:"sell",
              addressType:"public address",
              currency:"USD",
              crypto:"USDC",
              payment:"All Payments",
              price:1,
              available:319.325,
              min:25,
              max:3500,
            },
            {
                uid:"1",
                sellOfferNO:5,
                transactionType:"sell",
                addressType:"public address",
                currency:"USD",
                crypto:"USDC",
                payment:"All Payments",
                price:1,
                available:325.5,
                min:10,
                max:4000,
              },
            {
                uid:"2",
                sellOfferNO:8,
                transactionType:"sell",
                addressType:"public address",
                currency:"USD",
                crypto:"USDC",
                payment:"All Payments",
                price:1,
                available:2000,
                min:5,
                max:6000,
              },
        ],
        "THB":[
            {
                uid:"3",
                sellOfferNO:11,
                transactionType:"sell",
                addressType:"public address",
                currency:"THB",
                crypto:"USDC",
                payment:"Bank Transfer",
                price:32.24,
                available:50.35,
                min:800,
                max:480000,
            },
            {
                uid:"4",
                sellOfferNO:14,
                transactionType:"sell",
                addressType:"public address",
                currency:"THB",
                crypto:"USDC",
                payment:"Bank Transfer",
                price:32.27,
                available:8000,
                min:32,
                max:640000,
            },
            {
                uid:"5",
                sellOfferNO:17,
                transactionType:"sell",
                addressType:"public address",
                currency:"THB",
                crypto:"USDC",
                payment:"Bank Transfer",
                price:32.27,
                available:8000,
                min:32,
                max:640000,
            },
            {
                uid:"6",
                sellOfferNO:20,
                transactionType:"sell",
                addressType:"public address",
                currency:"THB",
                crypto:"USDC",
                payment:"Bank Transfer",
                price:32.30,
                available:8000,
                min:32,
                max:640000,
            },
        ]
    }
}
export default offering;